website = "http://www.tttthcs.com"
course = "Türkçe Python Rehberi: Baştan Sona Python Programlama Rehberi."

# uygulama_01 = course.upper()
# uygulama_02 = website.lstrip("t/h:p")
# uygulama_03 = course.lower()
# uygulama_04 = website.strip("htp:/wmoc")
# uygulama_05 = website.count("a")
# uygulama_06 = website.startswith("www")
# uygulama_07 = website.endswith("com")
# uygulama_08 = course.isalpha()
# uygulama_09 = course.replace("", "-")
# uygulama_10 = "Merhaba Dünya".replace("Dünya", "Acun")
uygulama_11 = course.split()

# print(uygulama_01)
# print(uygulama_02)
# print(uygulama_03)
# print(uygulama_04)
# print(uygulama_05)
# print(uygulama_06)
# print(uygulama_07)
# print(uygulama_08)
# print(uygulama_09)
# print(uygulama_10)
print(uygulama_11)
