import numpy as np

sayilar1 = np.array([10, 15, 30, 45, 60])
sayilar2 = np.arange(5, 15)
sayilar3 = np.arange(50, 100, 5)
sayilar4 = np.zeros(10)
sayilar5 = np.ones(10)
sayilar6 = np.linspace(0, 100, 5)
sayilar7 = np.random.randint(10 ,30, 5)
sayilar8 = np.random.randn(10)
sayilar9 = (np.random.randint(-50, 50, 15)).reshape(3, 5)
matris_satir = sayilar9.sum(axis=0)
matris_sutun = sayilar9.sum(axis=1)
matris_ortalama = sayilar9.mean()
matris_enkucuk = sayilar9.min()
matris_enbuyuk = sayilar9.max()
matris_enbuyuk_indis = sayilar9.argmax()
sayilar10 = np.arange(10, 20)
matris_ciftler = sayilar9[sayilar9 % 2 == 0]


print(sayilar1)
print(sayilar2)
print(sayilar3)
print(sayilar4)
print(sayilar5)
print(sayilar6)
print(sayilar7)
print(sayilar8)
print(sayilar9)
print(matris_satir)
print(matris_sutun)
print(matris_ortalama)
print(matris_enkucuk)
print(matris_enbuyuk)
print(matris_enbuyuk_indis)
print(sayilar10[:3])
print(sayilar10[::-1])
print(sayilar9[0])
print(sayilar9[1, 2])
print(sayilar9[:, 0])
print(sayilar9 ** 2)
print(matris_ciftler[matris_ciftler > 0])


